---
- name: Update and Patch Windows EC2 Instances
  hosts: Windows-server
  gather_facts: False
  tasks:
    - name: Install AWS SSM agent (optional if not already installed)
      win_shell: "Start-Process 'https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgent.msi' -ArgumentList '/qn' -Wait"

    - name: Update Windows packages
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        state: installed
      become: yes
      become_method: runas

    - name: Send update notification to AWS Patch Manager
      amazon.aws.aws_ssm:
        name: "AWS-RunPatchBaseline"
        instance_id: "{{ ansible_host }}"
        parameters:
          Operation: Install  # Use "Install" to install updates and trigger reboot (if required)
        region: "us-east-1"  # Replace with your desired AWS region
      become: yes
      become_method: runas
