---
- name: Update Windows EC2 and AWS SSM
  hosts: Windows-server
  become: yes
  gather_facts: yes

  tasks:
    - name: Update Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - FeaturePacks
        state: installed
      register: win_update_result

- name: Update AWS SSM
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Update SSM
      aws_ssm:
        name: all
        state: "latest"
      register: ssm_update_result

    - name: Print SSM update result
      debug:
        var: ssm_update_result
