---
- name: Patch Windows servers using AWS SSM
  hosts: Windows-server
  gather_facts: false
  tasks:
    - name: Check OS version and SSM agent version
      win_command: |
        echo if "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set "ps_arch=64") else (set "ps_arch=32")
        if %ps_arch%==32 (
            echo This command is not supported on Windows Desktop editions.
            exit 1
        )
        ver | findstr /i "5\.[0-9]\." > nul
        if %errorlevel% equ 0 (
            echo This command is not supported on this Windows version.
            exit 1
        )
        reg query "HKLM\SYSTEM\CurrentControlSet\Services\AmazonSSMAgent" > nul 2>&1
        if errorlevel 1 (
            echo This command is not supported with SSM Agent version less than 2.0.533.0.
            exit 1
        )
        echo Success
      register: os_check
      changed_when: false
      failed_when: false

    - name: Install PatchBaselineOperations PowerShell module
      win_command: Install-Module -Name PatchBaselineOperations -Force -ErrorAction Stop
      when: os_check.stdout == "Success"

    - name: Patch Windows servers
      win_command: Invoke-PatchBaselineOperation -Operation {{ operation }} -SnapshotId {{ snapshot_id }} -InstanceId %AWS_SSM_INSTANCE_ID% -Region %AWS_SSM_REGION_NAME%
      when: os_check.stdout == "Success" and module_install_result.rc == 0
      register: patch_result
      changed_when: false

    - name: Show patching results
      debug:
        var: patch_result
