---
- name: Patch Windows EC2 Instances
  hosts: Windows-server
  gather_facts: False
  tasks:
    - name: Install AWS SSM agent (optional if not already installed)
      win_shell: "Start-Process 'https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgent.msi' -ArgumentList '/qn' -Wait"

    - name: Patch Windows EC2 instances
      ssm:
        document_name: "AWS-InstallWindowsUpdates"
        instance_ids: "{{ ansible_host }}"
        region: "us-east-1"  # Replace with your desired AWS region
      become: yes
      become_method: runas
