- name: Update Windows EC2 instance
  hosts: Windows-server
  gather_facts: yes
  tasks:
    - name: Install Windows updates
      win_updates:
        category_names: 'SecurityUpdates,Updates'
        state: installed
      register: update_result

    - name: Reboot if updates were installed
      win_reboot:
      when: update_result.reboot_required | default(false)

    - name: Wait for the instance to come back online
      wait_for_connection:
        timeout: 300
