---
- name: Patch Windows EC2 and Update Patch Manager Dashboard
  hosts: Windows-server
  gather_facts: yes
  tasks:
    - name: Perform Windows update
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        state: installed
      register: update_result

    - name: Wait for Windows updates to complete
      async: 300
      poll: 0
      when: update_result | changed

    - name: Update Patch Manager Dashboard
      run_once: yes
      local_action:
        module: aws_ssm.create_association
        name: AWS-UpdateSSMAgent
        parameters:
          AutomationAssumeRole: "arn:aws:iam::{{ ansible_aws_account_id }}:role/YourPatchManagerAutomationRole"
          InstanceId: "{{ ansible_host }}"
